pipeline {
    agent {label 'MAIN'}

    stages {
        stage('Sonar') {
            steps {
                echo 'Scanning....'
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
